[HUDI-7016] Fix bundling of RoaringBitmap dependency (#9963)
This commit fixes the bundling of RoaringBitmap dependency in Hudi bundles by including it in the shade rules and shading the classes, to avoid dependency conflict with engine-provided jars, e.g., Spark. Before this fix, with Hudi Spark bundle, NoSuchMethodError exception is thrown by Spark 3.2.