[HUDI-5901][DOCS] Added links to understand in what cases HUDI Big Query integration works (#8091)
* Update gcp_bigquery.md

Why changes - In what cases the integration works is clear, finding elaboration of that cases can be made easier with links.
What are the Changes - Added links to understand in what cases HUDI Big Query integration works.

This change will help user to understand the restriction of integration faster.

* Update querying_data.md

Fixing build failure 

Error:  Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/querying_data:
   -> linking to /docs/next/query_engine_setup#redshift-spectrum (resolved as: /docs/next/query_engine_setup)
   -> linking to /docs/next/query_engine_setup#doris (resolved as: /docs/next/query_engine_setup)
   -> linking to /docs/next/query_engine_setup#starrocks (resolved as: /docs/next/query_engine_setup)

    at reportMessage (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/utils/lib/index.js:306:19)
    at handleBrokenLinks (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/core/lib/server/brokenLinks.js:138:35)
    at async buildLocale (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/core/lib/commands/build.js:155:5)
    at async tryToBuildLocale (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/core/lib/commands/build.js:33:20)
    at async mapAsyncSequencial (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/utils/lib/index.js:262:24)
    at async build (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
Error: Process completed with exit code 1.