Cleaning up unnecessary relocation for com.google.common packages (#7900)
Addresses an issue of following relocations configs in MR/Spark bundles stranded after removal of Guava from Hudi Spark and MR bundles:

```
<relocation>
  <pattern>com.google.common.</pattern>
  <shadedPattern>org.apache.hudi.com.google.common.</shadedPattern>
</relocation> 
```

Such relocations entailed that all references from any class (included into the Hudi bundle) referencing Guava would be shaded, even though Hudi isn't packaging Guava anymore, potentially resulting in exception when these classes try to access Guava provided by Spark for ex:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/hudi/com/google/common/base/Preconditions
	at org.apache.curator.ensemble.fixed.FixedEnsembleProvider.<init>(FixedEnsembleProvider.java:39)
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.connectString(CuratorFrameworkFactory.java:193)
	at org.apache.kyuubi.ha.client.zookeeper.ZookeeperClientProvider$.buildZookeeperClient(ZookeeperClientProvider.scala:62)
	at org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient.<init>(ZookeeperDiscoveryClient.scala:65)
	... 45 more 
```